name: Build and Release APK

on:
  schedule:
    - cron: '0 0 */3 * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Gradle packages
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Get commit info
        id: commit
        run: |
          echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
          
          COMMITS=$(git log --since="3 days ago" --no-merges --pretty=format:"- %s (%h)")
          
          if [ -z "$COMMITS" ]; then
            COMMITS="- Manual launch or no changes"
          fi
          
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$COMMITS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew assembleRelease -PciVersionCode=${{ github.run_number }} -PciVersionName="${{ github.run_number }}-${{ steps.commit.outputs.hash }}"

      - name: Sign APK
        uses: r0adkll/sign-android-release@v1
        id: sign_app
        with:
          releaseDirectory: app/build/outputs/apk/release
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.KEY_ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
          buildToolsVersion: 34.0.0

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build-alpha-${{ github.run_number }}
          name: Build ${{ steps.commit.outputs.hash }} (${{ github.run_number }})
          prerelease: true
          files: ${{steps.sign_app.outputs.signedReleaseFile}}
          body: |
            ## Changes in this build:
            
            ${{ steps.commit.outputs.body }}
            
            ---
            🔗 Commit: ${{ steps.commit.outputs.hash }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
